### ISSUE TITLE
自定義雙拼方案

### ISSUE THREAD

**Issue by RomaYun323** [ksqsf/rime-moran#41]
您好，感謝製作魔然方案
想請教若是想將自然碼雙拼轉為小鶴雙拼要如何修改呢？謝謝。

**Comment by ksqsf** [comment]
您好，這個操作比較複雜，下面給出簡單的說明：

方案有兩部分：
1. 整句詞庫： moran.extended.dict.yaml 及其所引用的 dict.yaml
2. 簡碼詞庫： moran_fixed.dict.yaml 和 moran_fixed_simp.dict.yaml

「魔然」方案使用了這兩種詞庫，「整句」僅使用前者，「字詞」僅使用後者。

這兩種詞庫格式不同，因此操作流程不同。

## 整句詞庫

打開 moran.yaml，修改 `user_sentence_top` 處的 algebra 即可。

下面是一個例子：

```yaml
  user_sentence_top:
    __append: # 注意這一行必須保留
      - derive/^([a-z]+);/\U$1;/   # 雙拼編碼轉大寫以避免衝突，如 vd;yd -> VD;yd

      # ...下面需要一一把自然碼雙拼替換成小鶴雙拼
      - xform/^VL/vd/  # zhai: 把自然碼雙拼 vl 替換成小鶴雙拼 vd
      - xform/^VD/vl/  # zhuang: 把自然碼雙拼 vd 替換成小鶴雙拼 vl
      - xform/^BN/bb/  # bin: 把自然碼雙拼 bn 替換成小鶴雙拼 bb
      - xform/^SB/sz/  # sou: 把自然碼雙拼 sb 替換成小鶴雙拼 sz
      # ......

      - xlit/ABCDEFGHIJKLMNOPQRSTUVWXYZ/abcdefghijklmnopqrstuvwxyz/  # 大寫轉回小寫
```

只需要補全其中的雙拼替換即可，第一行和最後一行可不變。

做完這一步後，「魔然」和「整句」方案中的整句詞庫雙拼就已經全部轉換爲小鶴雙拼了。

## 簡碼詞庫

簡碼由於存在壓縮情況，無法使用 algebra 統一處理，因而需要重新製作。可參考 #30 中的描述。

最後，如果沒有特殊需求，也可以考慮使用小鶴雙拼的類似配置： https://github.com/gaboolic/rime-shuangpin-fuzhuma
