### ISSUE TITLE
如何设定为原始的自然码双拼方案

### ISSUE THREAD

**Issue by soiamsoNG** [ksqsf/rime-moran#52]
请问如何设定为原始的自然码双拼方案
作为韵母的时候 v = ü

是否可以增加到FQA里面

**Comment by ksqsf** [comment]
编辑 moran.yaml 修改其中的 `user_sentence_top` 部分：

```
  user_force_bottom:
    __append:
      __patch:
        - moran_defs:/classic_zrm_jqx
```
