### ISSUE TITLE
固词模式+开启固定单字+禁用固定多字词+禁用出简让全+开启词语级辅助，四码不显示候选

### ISSUE THREAD

**Issue by davidlauhn** [ksqsf/rime-moran#96]
小狼毫 0.16.1
魔然 2.0.2

```yaml
#moran.custom.yaml
patch:
  moran/enable_word_filter: true
  moran/show_chars_anyway: true
  moran/show_words_anyway: false
  moran/ijrq/enable: false
```
看了说明书，本想实现 魔然方案的 「碼表中的單字和二字詞優先輸出」可在固词模式开启的时候 `moran/show_words_anyway` 和 `moran/show_chars_anyway` 同时开启或同时禁用都没有问题，只开启 `moran/show_chars_anyway` 就出问题了，为了确定自己的配置没有问题，卸载重装问题依旧，四码不显示候选，比如，`womf` `ceui`，不知道是不是我哪里没有配置对？谢谢
